[package]
name = "spotify-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.79"
web-sys = "0.3.56"
yew = "0.19.3"
yew-router = "0.16.0"
